export const URGENCY = [
  { id: "now", label: "Now", color: "#B5462A" },
  { id: "soon", label: "Soon", color: "#A8791A" },
  { id: "later", label: "Later", color: "#3E6B52" },
];

export const DEFAULT_PROJECTS = [
  "MTO / Compass IoT",
  "Side Engineering",
  "Finance",
  "Church/Service",
  "Admin",
  "Other",
];

export const styles = {
  page: { fontFamily: "ui-sans-serif, system-ui, -apple-system, sans-serif", background: "#F7F6F3", color: "#1C2024", padding: "24px", minHeight: "100vh", maxWidth: "980px", margin: "0 auto" },
  loading: { padding: 40, fontFamily: "ui-sans-serif, system-ui, sans-serif", color: "#5A6069" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 14, flexWrap: "wrap", gap: 10 },
  eyebrow: { fontSize: 20, fontWeight: 600, letterSpacing: "-0.01em" },
  count: { fontSize: 13, color: "#6B7280", marginTop: 2, fontFamily: "ui-monospace, SFMono-Regular, monospace" },
  headerActions: { display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" },
  viewBtn: { display: "flex", alignItems: "center", gap: 5, padding: "6px 11px", borderRadius: 100, border: "1px solid #DADDE1", background: "#fff", fontSize: 12, color: "#4B5563", cursor: "pointer" },
  viewBtnActive: { borderColor: "#2C5F8A", color: "#2C5F8A", background: "#EAF1F7" },
  iconBtn: { display: "flex", alignItems: "center", gap: 5, padding: "6px 11px", borderRadius: 100, border: "1px solid #DADDE1", background: "#fff", fontSize: 12, color: "#4B5563", cursor: "pointer" },
  doneToggle: { fontSize: 12, color: "#6B7280", display: "flex", gap: 6, alignItems: "center", cursor: "pointer", marginLeft: "auto" },
  visLabel: { fontSize: 12, color: "#9CA3AF", alignSelf: "center", marginRight: 2 },
  visChip: { fontSize: 12, color: "#4B5563", display: "flex", gap: 5, alignItems: "center", cursor: "pointer", padding: "5px 10px", border: "1px solid #DADDE1", borderRadius: 100, background: "#fff" },
  form: { display: "flex", gap: 8, marginBottom: 14, flexWrap: "wrap" },
  textInput: { flex: "1 1 200px", padding: "9px 12px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 14, background: "#fff" },
  projectInput: { width: 150, padding: "9px 10px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  dateInput: { padding: "9px 10px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  timeInput: { padding: "9px 10px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  locationInput: { width: 140, padding: "9px 10px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  select: { padding: "9px 10px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  addBtn: { display: "flex", alignItems: "center", gap: 6, padding: "9px 14px", background: "#2C5F8A", color: "#fff", border: "none", borderRadius: 6, fontSize: 13, fontWeight: 600, cursor: "pointer" },
  filterRow: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 12, alignItems: "center" },
  chip: { padding: "5px 11px", borderRadius: 100, border: "1px solid #DADDE1", background: "#fff", fontSize: 12, color: "#4B5563", cursor: "pointer" },
  chipActive: { borderColor: "#2C5F8A", color: "#2C5F8A", background: "#EAF1F7" },
  errorBanner: { background: "#FCEEEA", color: "#9A3412", padding: "8px 12px", borderRadius: 6, fontSize: 12, marginBottom: 12 },
  infoBanner: { background: "#EAF1F7", color: "#234b6e", padding: "10px 12px", borderRadius: 6, fontSize: 12, marginBottom: 14, lineHeight: 1.5 },
  tabBar: { display: "flex", gap: 4, marginBottom: 16, borderBottom: "1px solid #E7E5E0" },
  tabBtn: { display: "flex", alignItems: "center", gap: 6, padding: "9px 14px", background: "none", border: "none", borderBottom: "2px solid transparent", fontSize: 13, color: "#6B7280", cursor: "pointer", fontWeight: 500 },
  tabBtnActive: { color: "#2C5F8A", borderBottomColor: "#2C5F8A" },
  tabCount: { fontFamily: "ui-monospace, monospace", fontSize: 11, color: "#9CA3AF" },
  sectionsWrap: { display: "flex", flexDirection: "column", gap: 26 },
  section: {},
  sectionHeader: { display: "flex", alignItems: "center", gap: 8, fontSize: 14, fontWeight: 600, marginBottom: 12, color: "#1C2024" },
  sectionCount: { marginLeft: "auto", fontFamily: "ui-monospace, monospace", fontSize: 11, color: "#9CA3AF", fontWeight: 400 },
  column: { background: "#FCFBF9", border: "1px solid #E7E5E0", borderRadius: 10, padding: 12, minHeight: 140 },
  columnHeader: { display: "flex", alignItems: "center", gap: 7, fontSize: 13, fontWeight: 600, marginBottom: 10, color: "#374151" },
  columnCount: { marginLeft: "auto", fontFamily: "ui-monospace, monospace", fontSize: 11, color: "#9CA3AF" },
  dot: { width: 8, height: 8, borderRadius: "50%", display: "inline-block" },
  columnBody: { display: "flex", flexDirection: "column", gap: 7 },
  listBody: { display: "flex", flexDirection: "column", gap: 7 },
  groupHeader: { fontSize: 11, fontWeight: 600, color: "#9CA3AF", margin: "10px 0 4px" },
  empty: { fontSize: 12, color: "#B0B4BA", padding: "10px 2px" },
  taskCard: { display: "flex", gap: 8, alignItems: "flex-start", background: "#fff", border: "1px solid #E7E5E0", borderRadius: 7, padding: "8px 9px" },
  taskDone: { background: "#F7F6F3" },
  checkBtn: { width: 18, height: 18, borderRadius: "50%", border: "1.5px solid #C6CAD1", background: "#fff", display: "flex", alignItems: "center", justifyContent: "center", color: "#9CA3AF", flexShrink: 0, cursor: "pointer", marginTop: 1 },
  taskBody: { flex: 1, minWidth: 0 },
  taskTitle: { fontSize: 13, lineHeight: 1.35, wordBreak: "break-word" },
  taskMeta: { fontSize: 10.5, color: "#9CA3AF", marginTop: 2, fontFamily: "ui-monospace, monospace" },
  metaLoc: { marginLeft: 6 },
  badge: { fontSize: 10.5, fontFamily: "ui-monospace, monospace", border: "1px solid", borderRadius: 100, padding: "2px 7px", flexShrink: 0, marginTop: 1, whiteSpace: "nowrap" },
  delBtn: { background: "none", border: "none", color: "#C6CAD1", cursor: "pointer", flexShrink: 0, marginTop: 1 },
  doneSection: { marginTop: 14, borderTop: "1px solid #E7E5E0", paddingTop: 12 },
  doneHeader: { fontSize: 12, fontWeight: 600, color: "#9CA3AF", marginBottom: 8 },
  authWrap: { maxWidth: 360, margin: "80px auto", fontFamily: "ui-sans-serif, system-ui, -apple-system, sans-serif" },
  authCard: { background: "#fff", border: "1px solid #E7E5E0", borderRadius: 10, padding: 24 },
  authTitle: { fontSize: 18, fontWeight: 600, marginBottom: 4 },
  authSub: { fontSize: 13, color: "#6B7280", marginBottom: 18 },
  authField: { width: "100%", boxSizing: "border-box", padding: "9px 12px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 14, marginBottom: 10 },
  authBtn: { width: "100%", padding: "10px 14px", background: "#2C5F8A", color: "#fff", border: "none", borderRadius: 6, fontSize: 14, fontWeight: 600, cursor: "pointer", marginTop: 4 },
  authSwitch: { fontSize: 12.5, color: "#6B7280", marginTop: 14, textAlign: "center" },
  authLink: { color: "#2C5F8A", cursor: "pointer", fontWeight: 600 },
  authError: { fontSize: 12.5, color: "#9A3412", marginTop: 4, marginBottom: 6 },
  authNotice: { fontSize: 12.5, color: "#234b6e", background: "#EAF1F7", padding: "8px 10px", borderRadius: 6, marginTop: 10 },
  settingsPanel: { background: "#fff", border: "1px solid #E7E5E0", borderRadius: 10, padding: 16, marginBottom: 18, fontSize: 13 },
  settingsRow: { display: "flex", gap: 8, alignItems: "center", marginTop: 8, flexWrap: "wrap" },
  urlBox: { flex: "1 1 260px", padding: "8px 10px", background: "#F7F6F3", border: "1px solid #E7E5E0", borderRadius: 6, fontFamily: "ui-monospace, monospace", fontSize: 11.5, wordBreak: "break-all" },

  fieldGroup: { display: "flex", flexDirection: "column", gap: 3 },
  fieldLabel: { fontSize: 10.5, fontWeight: 600, color: "#9CA3AF", textTransform: "uppercase", letterSpacing: "0.02em" },
  categoryAddRow: { display: "flex", gap: 6, alignItems: "center" },

  smartBar: { display: "flex", gap: 4, marginBottom: 12 },
  smartBtn: { display: "flex", alignItems: "center", gap: 5, padding: "6px 12px", borderRadius: 100, border: "1px solid #DADDE1", background: "#fff", fontSize: 12.5, color: "#4B5563", cursor: "pointer" },
  smartBtnActive: { borderColor: "#2C5F8A", color: "#2C5F8A", background: "#EAF1F7" },
  smartCount: { fontFamily: "ui-monospace, monospace", fontSize: 10.5, color: "#9CA3AF" },
  prioritySelect: { padding: "9px 8px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  notesInput: { flex: "1 1 100%", padding: "9px 12px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 13, background: "#fff" },
  flagBtn: { background: "none", border: "none", cursor: "pointer", flexShrink: 0, marginTop: 1, padding: 2, color: "#D8DCE1" },
  flagBtnActive: { color: "#A8791A" },
  priorityTag: { fontSize: 10.5, fontFamily: "ui-monospace, monospace", fontWeight: 700, marginLeft: 6 },
  expandBtn: { background: "none", border: "none", cursor: "pointer", color: "#B0B4BA", flexShrink: 0, marginTop: 1, padding: 2 },
  expandedPanel: { marginTop: 8, paddingTop: 8, borderTop: "1px dashed #E7E5E0", display: "flex", flexDirection: "column", gap: 8 },
  notesArea: { width: "100%", boxSizing: "border-box", padding: "7px 9px", border: "1px solid #DADDE1", borderRadius: 6, fontSize: 12.5, fontFamily: "inherit", resize: "vertical", minHeight: 50 },
  subtaskLabel: { fontSize: 11, fontWeight: 600, color: "#9CA3AF" },
  subtaskRow: { display: "flex", alignItems: "center", gap: 7 },
  subtaskCheck: { width: 15, height: 15, borderRadius: 4, border: "1.5px solid #C6CAD1", background: "#fff", display: "flex", alignItems: "center", justifyContent: "center", color: "#9CA3AF", flexShrink: 0, cursor: "pointer" },
  subtaskTitle: { fontSize: 12.5, flex: 1 },
  subtaskAddRow: { display: "flex", gap: 6, marginTop: 2 },
  subtaskAddInput: { flex: 1, padding: "6px 8px", border: "1px solid #DADDE1", borderRadius: 5, fontSize: 12.5 },
  subtaskAddBtn: { padding: "6px 10px", border: "1px solid #DADDE1", borderRadius: 5, background: "#fff", fontSize: 12, cursor: "pointer", color: "#4B5563" },
};
